/**
 *
 * $Id$
 */
package RiskMatrixModel.validation;

import RiskMatrixModel.LikelihoodLevel;
import RiskMatrixModel.SeverityLevel;

/**
 * A sample validator interface for {@link RiskMatrixModel.RiskRatingInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RiskRatingInstanceValidator {
	boolean validate();

	boolean validateRiskValue(int value);

	boolean validateRiskValue(float value);
	boolean validateLikelihoodlevel(LikelihoodLevel value);
	boolean validateSeveritylevel(SeverityLevel value);
}
