/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.HazardRepository;
import careProcess_model.LocationRepository;
import careProcess_model.ReportData;
import careProcess_model.SystemRepository;

/**
 * A sample validator interface for {@link careProcess_model.DataStore}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataStoreValidator {
	boolean validate();

	boolean validateLocationrepository(LocationRepository value);
	boolean validateSystemrepository(SystemRepository value);
	boolean validateHazardrepository(HazardRepository value);
	boolean validateReportData(ReportData value);
}
