/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.HazardCause;
import careProcess_model.HazardControl;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.HazardCause}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HazardCauseValidator {
	boolean validate();

	boolean validateHazardcauses(EList<HazardCause> value);
	boolean validateCauseName(String value);
	boolean validateCauseDescription(String value);
	boolean validateHazardcontrols(EList<HazardControl> value);
}
