/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.ControlStateEnum;
import careProcess_model.ControlTypeEnum;
import careProcess_model.HazardCause;
import careProcess_model.HazardEffect;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.HazardControl}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HazardControlValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateName(String value);
	boolean validateControlState(ControlStateEnum value);
	boolean validateControlTypes(EList<ControlTypeEnum> value);
	boolean validateOtherText(String value);
	boolean validateHazardcause(HazardCause value);
	boolean validateHazardeffect(HazardEffect value);
}
