/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.CareProcess;
import careProcess_model.Step;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.processGraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface processGraphValidator {
	boolean validate();

	boolean validateCareProcess(CareProcess value);
	boolean validateGraphData(String value);
	boolean validateDataMap(String value);
	boolean validateStep(EList<Step> value);
}
