/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.CareProcess;
import careProcess_model.DataStore;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.Project}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProjectValidator {
	boolean validate();

	boolean validateCareProcesses(EList<CareProcess> value);
	boolean validateDatastore(DataStore value);
	boolean validateDateModified(XMLGregorianCalendar value);
	boolean validateAcceptableHazardDefinition(String value);
	boolean validateCreatedWithAppVersion(String value);
	boolean validateRiskMatrixData(String value);
}
