/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.IssueDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.ReportData}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReportDataValidator {
	boolean validate();

	boolean validateIssueDefinitions(EList<IssueDefinition> value);
	boolean validateReportIntroductionText(String value);
	boolean validateCrmSystemText(String value);
	boolean validateSummarySafetyStatementText(String value);
	boolean validateQaAndDocApprovalText(String value);
	boolean validateConfigurationControlText(String value);
	boolean validateReportTitleText(String value);
}
