/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.HazardInstance;
import careProcess_model.LocationDefinition;
import careProcess_model.Step;
import careProcess_model.SystemFunction;
import careProcess_model.processGraph;
import careProcess_model.stepType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.Step}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StepValidator {
	boolean validate();

	boolean validateSuccessors(EList<Step> value);
	boolean validateStepTypeValue(stepType value);
	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateHazardInstances(EList<HazardInstance> value);
	boolean validateLocation(LocationDefinition value);
	boolean validateAssociatedSystemFunctions(EList<SystemFunction> value);
	boolean validateUUID(String value);
	boolean validateProcessGraph(processGraph value);
	boolean validateHidden(boolean value);
}
