/**
 *
 * $Id$
 */
package careProcess_model.validation;

import careProcess_model.SystemFunction;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link careProcess_model.SystemDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemDefinitionValidator {
	boolean validate();

	boolean validateSystemName(String value);
	boolean validateMnemonicName(String value);
	boolean validateSystemFunctions(EList<SystemFunction> value);
	boolean validateSystemVersion(String value);
	boolean validateSystemDescription(String value);
}
